require('custom.hot-reload')
require('custom.keymapper')
require('custom.null-ls')
require('custom.which-key')
require('custom.packer')
require('custom.yank')
require('custom.set')
require('custom.comment')
require('custom.indent-blankline')
require('custom.gitsigns')
require('custom.telescope')
require('custom.nvim-treesitter')
require('custom.lsp-config')
-- require('custom.lua-line')

